### PR TITLE
#35 Pick testing libraries and create a very simple test

### LINKED ISSUE #35: Set up testing
Each module should have tests and there should be integration tests against the services.

- Add tests to each module
- Write example integration tests
- Ensure all tests are run on CI

### PR DESCRIPTION
**Pull request by ThetaSinner**
Resolves #35 

Opening PR after first commit to my work is visible

### CODE REVIEW

**Comment by ThetaSinner** [comment]
Ready to review pending successful build.

There are some classes in the service layer not covered and I've only written tests for linking datastores to a network and not appsoft or syssoft.
I'll create a separate task for setting up integration testing in the interest of getting this monster merged!

**Comment by Sub-Xaero** [comment]
Resolve conflicts and then this is good to go.

**Comment by ThetaSinner** [comment]
What conflicts? Why is your GitHub broken???

**Comment by Sub-Xaero** [comment]
I blame Microsoft.

**Pull request merged**
