### PR TITLE
#10 create persistence for connections

### PR DESCRIPTION
**Pull request by ThetaSinner**
Creating PR for visibility

### CODE REVIEW

**Comment by ThetaSinner** [comment]
I've used an interface with an enum class instead of reflection. So still have strong types but I'm missing the ability to join on lookup. Need to work through implementing the lookup for this type

**Comment by ThetaSinner** [comment]
Ready for review

**Comment by Sub-Xaero** [comment]
I'll take your word for it. Nothing obviously wrong, will assume technical details all correct.

**Comment by ThetaSinner** [comment]
Haha, my word is good. But yeah it's definitely missing things but certainly works :-)

**Pull request merged**
