### PR TITLE
Circle CI

### PR DESCRIPTION
**Pull request by Sub-Xaero**

### CODE REVIEW

**Comment by ThetaSinner** [comment]
Shouldn't be necessary to install the Kotlin compiler. It should be bundled with the Gradle plugins.

Otherwise looks great, please add a build status badge to the readme once it's working

**Comment by Sub-Xaero** [comment]
capture

Is there a way to enable it then? It's not visible by default.

**Comment by Sub-Xaero** [comment]
Whereas downloading and PATH-ing it: 
image

**Comment by ThetaSinner** [comment]
Yeah it absolutely won't be visible, ```gradle build``` should work without Kotlin being available.

The other thought I had, sorry for this, is that there's no need to isntall Gradle. You can just use the checked in Gradle wrapper.
So you can just run ```gradlew build``` in the root and it will download gradle if not found

**Comment by Sub-Xaero** [comment]
Ah ok, didn't realise we were doing that. Okay. We'd still need a Java runtime though right? 
So 
 - Docker
   - a base UNIX image
   - install JDK
 - Entrypoint for Circle
   - checkout project
   - gradlew build
   - Test, once testing is a thing

**Pull request merged**
